### PR TITLE
Mituron/adding acc validator to examples

### PR DESCRIPTION
**Pull request by kolaps33**
# [Accessibility validator on example]

Integrating Axe-core accessibility validator for each example. 
https://axe-core.org/docs/

Validator took particular example/element(s) and return report. 

Report will be displayed in the same way as others features are displayed("Try it" or "Theme it")

Screenshot from localhost:
image

### CODE REVIEW

**Comment by codepretty** [comment]
There is a bug where if I have 'Try it' selected & 'Accessibility', then if I close 'Try it' the Accessibility output will also close. Same thing happens with 'Theme it' & 'Accessibility'. Also, every time I click the Accessibility button it jumps to the top of the page.

**Comment by codepretty** [comment]
Every time I click the Accessibility button it jumps to the top of the page.

**Comment by levithomason** [comment]
This seems like something we should bake into tests.  We want this type of check, but it isn't helpful to end users which is the goal of the examples.

Note that we'll be adding Screener.io image comparison tests for each example as well.  So, we'll have a mechanism for testing each example in isolation.

Thoughts on baking this into some kind of test pass?

**Comment by kolaps33** [comment]
This PR will be not implemented as we move this logic to unit tests.

**Pull request closed without merging**
