### PR TITLE
docs: add glossary to specifications

### PR DESCRIPTION
**Pull request by levithomason**
# ⚠️ From: https://github.com/stardust-ui/react-old/pull/71

### CODE REVIEW

**Comment by Bugaa92** [comment]
My proposal for spacing:

`xSpacing=['none'|'before'|'after'|'both']`
`ySpacing=['none'|'before'|'after'|'both']`

already implemented for Icon here #22 

@mnajdova @levithomason

**Comment by mnajdova** [comment]
For the components that can contain some removable icon, using the convention from SUI we can use the onRemove and removeIcon props. (implemented in the PR for the removable Label) https://github.com/stardust-ui/react/pull/19

**Comment by levithomason** [comment]
See #39 for `xSpacing` / `fitted` proposal and discussion.

**Comment by levithomason** [comment]
This is now being handled in the documentation PRs.  This information is being added to the doc site instead of as markdown.  The props and descriptions are also going to be available in the doc site opposed to markdown.

**Pull request closed without merging**
