### PR TITLE
fix(build): remove prepush

### LINKED ISSUE #1102: Do not check git tags in prepush
### Steps
```sh
$ gp              
husky > npm run -s prepush (node v8.11.3)

[11:22:15] Requiring external module ts-node/register
[11:22:24] Using gulpfile ~/devel/stardust-ui-react/gulpfile.ts
[11:22:24] Starting 'git:prepush'...
[11:22:24] Finished 'git:prepush' after 19 ms
```

prepush checks tags. The check was necessary to keep integrity of tags after moving from semantic-ui/react. It is hopefully no longer necessary, remove the step to save up to 10s with every push

### PR DESCRIPTION
**Pull request by miroslavstastny**
Remove prepush step as it is no longer needed.
Fixes #1102

### CODE REVIEW

**Comment by mnajdova** [comment]
I am still seeing the pre-push failing sometimes, and I have to remove and pull all tags again... Not sure if this is the case with other developers..

**Comment by kuzhelov** [comment]
in that case lets take a look on @mnajdova 's case and leave this functionality till the end of investigation - @miroslavstastny, what do you think?

**Comment by miroslavstastny** [comment]
We do not have an agreement that we can remove this.

**Comment by miroslavstastny** [comment]
We believe we have an agreement now, reopening...

**Review by layershifter — APPROVED** [review]

**Pull request merged**
