### PR TITLE
feat(icon): Add and export new compose icons

### PR DESCRIPTION
**Pull request by joheredi**
This PR adds and exports a set of new icons for compose
image

### CODE REVIEW

**Comment by kuzhelov** [comment]
note, you are creating PR with the wrong target - it should be just `master` (not `stardust:master`, no colons):

image

**Comment by joheredi** [comment]
> note, you are creating PR with the wrong target - it should be just `master` (not `stardust:master`, no colons):
> 
> image

@kuzhelov  Thanks for pointing this out. I'll create a new PR, is this the right way?
image

**Comment by joheredi** [comment]
> > note, you are creating PR with the wrong target - it should be just `master` (not `stardust:master`, no colons):
> > image
> 
> @kuzhelov Thanks for pointing this out. I'll create a new PR, is this the right way?
> image

@kuzhelov I think it shows as `stardust-ui:master` because I'm merging from my Fork. I'm not an "official" contributor so I couldn't create a branch within the main fork.

**Comment by joheredi** [comment]
Submitting a new Pull Request against master

**Pull request closed without merging**
