### PR TITLE
fix: replacing usage of className with styles

### PR DESCRIPTION
**Pull request by mnajdova**
# Fix for styling the components

This PR ensures property usage of the styles object, that are now available in the renderComponent method. Replaced in all components applicable except of Menu, MenuItem, ListItem that are taken care of in other PRs.

### TODO

- [x] Conformance test
- [ ] Minimal doc site example
- [ ] Stardust base theme
- [ ] Teams Light theme
- [ ] Teams Dark theme
- [ ] Teams Contrast theme
- [ ] Confirm RTL usage
- [ ] [W3 accessibility](https://www.w3.org/standards/webdesign/accessibility) check
- [ ] [Stardust accessibility](https://github.com/stardust-ui/accessibility) check
- [ ] Update glossary props table
- [ ] Update the CHANGELOG.md

# Proposal for fixing

Replacing the className={classes.componentPart} with styles={ root: styles.componentPart}. This can also be improved by describing the component parts in the styles in the following manner:
```
{
   root: ....,
   componentPart: {
     root: {
       //some styles
     },
     subcomponentPart: {
       //other styles for the subcomponent part
     },
  }
}
```

With this we can just apply the styles in the following manner: styles={styles.componentPart} and would be consistent through all component. I am just not sure if this will be used in that manner. Any thoughts on this?

### CODE REVIEW

**Comment by kuzhelov** [comment]
@mnajdova, thanks a lot for addressing this issue!

In regards to the proposal you've suggested: the only thing I am worrying about is that this approach will introduce quite strong coupling between component itself and its child. Just as an example: suppose that we are considering Avatar component, where the following styles should be introduced (according to the suggestion's semantics):

```js
const avatarStyles = {
   root: ...,
   avatarImage: (...) => {
      root: ...,
      imagePart: ...,
      anotherImagePart: ...,
  }
}
```

With this implementation Avatar component should be absolutely sure that `imagePart` and `anotherImagePart` will be always used for the component that is rendered at image's place (it could be Image component initially, but what if it will be changed to AvatarImage component as time will pass - the one that won't have any of these `imagePart` or `anotherImagePart`?)

----------

With that being said, I totally agree that we need to simplify usage patterns on the consumer side. My proposal would be to make it possible to pass an object to styles, without explicitly mentioning that those are styles for 'root' part:

```jsx
const imageStyles = {
   margin: 0,
   ...
}
...

<Avatar>
   ...
   <SomeImageComponent styles={imageStyles} />
  // this should be treated as equivalent to <SomeImageComponent styles={{ root: imageStyles }} />
   ...
</Avatar>
```

With that it seems that we will solve the problem you are talking about, without introducing additional nesting level (and possibility for increased inter-component coupling) to our implementation.

Please, share your thoughts on this.

**Comment by mnajdova** [comment]
I agree for the coupling, that is good point. Another point for the first approach is the simplicity in defining the styles, that is why I started with this approach. Regarding the styles as prop to be threated as root style, if the root is not provided, I am for it. @levithomason can you share your thoughts on this?

**Review by levithomason — APPROVED** [review]

**Comment by levithomason** [comment]
Yes, I also have had this thought in working with styles, that the root style should be the default.  

Let's introduce this in another PR.  This PR is about fixing classNames which the current code does well.

**Comment by levithomason** [comment]
@kuzhelov, looks like you're pushing to a merged branch.  Was this a mistake or do we need to migrate any changes to a new PR?

**Pull request merged**
