### PR TITLE
docs(Examples): fix Grid variables to fix gaps in Firefox

### PR DESCRIPTION
**Pull request by notandrew**
after:
image

before:
image

### CODE REVIEW

**Review by layershifter — COMMENTED** [review]
Actually, this change is more than an update for because it affects also `base` theme and `teams` theme. These values were introduced in the initial PR #93, however I am not sure that we need them at all.

@Bugaa92 @kuzhelov can we safely remove them? See #1440 for Screener test run.

**Comment by bmdalex** [comment]
> Actually, this change is more than an update for because it affects also `base` theme and `teams` theme. These values were introduced in the initial PR #93, however I am not sure that we need them at all.
> 
> @Bugaa92 @kuzhelov can we safely remove them? See #1440 for Screener test run.

@layershifter I cannot see the screener test results... I remember it was not safe to remove them because of issues with IE and Edge, did you test there?

**Comment by layershifter** [comment]
> I cannot see the screener test results... 
https://screener.io/v2/dashboard/5b6d198a6b2944400b00fb25/try%2Fempty-values

**Comment by bmdalex** [comment]
> > I cannot see the screener test results...
> > https://screener.io/v2/dashboard/5b6d198a6b2944400b00fb25/try%2Fempty-values

what about IE and Edge? @layershifter

**Comment by notandrew** [comment]
@layershifter @Bugaa92  - not sure what to do with this PR...

**Comment by codepretty** [comment]
@layershifter @levithomason do you know if we plan to have screener support for other browsers?

**Review by layershifter — APPROVED** [review]
Tested it in FF & Edge, works fine.
There are issues in IE11, but they related to CSS Grid module at all.

**Pull request merged**
